apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - image: {{ .Values.IMAGE.NAME }}:{{ .Values.IMAGE.TAG }}
          name: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: {{ .Values.MYSQL_ROOT_PASSWORD }}
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pv-neone
