apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: {{ .Values.STORAGE_SIZE }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"