apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-neone
  labels:
    type: mysql-pv-claim
spec:
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: {{ .Values.STORAGE_SIZE }}